/*

    Copyright 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020  joshua.tee@gmail.com

    This file is part of wX.

    wX is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    wX is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with wX.  If not, see <http://www.gnu.org/licenses/>.

 */

package joshuatee.wx.settings

import android.content.Context
import androidx.preference.PreferenceManager

object UtilityPref {

    fun prefInitBig(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("NWS_RID_JSJ", null)
        if (value == null) {
            editor.putString("NWS_RID_ABQ", "ABX")
            editor.putString("NWS_RID_ABR", "ABR")
            editor.putString("NWS_RID_AFC", "AHG")
            editor.putString("NWS_RID_AFG", "APD")
            editor.putString("NWS_RID_AJK", "ACG")
            editor.putString("NWS_RID_AKQ", "AKQ")
            editor.putString("NWS_RID_ALY", "ENX")
            editor.putString("NWS_RID_AMA", "AMA")
            editor.putString("NWS_RID_ANC", "ANC")
            editor.putString("NWS_RID_APX", "APX")
            editor.putString("NWS_RID_ARX", "ARX")
            editor.putString("NWS_RID_BGM", "BGM")
            editor.putString("NWS_RID_BIS", "BIS")
            editor.putString("NWS_RID_BMX", "BMX")
            editor.putString("NWS_RID_BOI", "CBX")
            editor.putString("NWS_RID_BOU", "FTG")
            editor.putString("NWS_RID_BOX", "BOX")
            editor.putString("NWS_RID_BRO", "BRO")
            editor.putString("NWS_RID_BTV", "CXX")
            editor.putString("NWS_RID_BUF", "BUF")
            editor.putString("NWS_RID_BYZ", "BLX")
            editor.putString("NWS_RID_CAE", "CAE")
            editor.putString("NWS_RID_CAR", "CBW")
            editor.putString("NWS_RID_CHS", "CLX")
            editor.putString("NWS_RID_CLE", "CLE")
            editor.putString("NWS_RID_CRP", "CRP")
            editor.putString("NWS_RID_CTP", "CCX")
            editor.putString("NWS_RID_CYS", "CYS")
            editor.putString("NWS_RID_DDC", "DDC")
            editor.putString("NWS_RID_DLH", "DLH")
            editor.putString("NWS_RID_DMX", "DMX")
            editor.putString("NWS_RID_DTX", "DTX")
            editor.putString("NWS_RID_DVN", "DVN")
            editor.putString("NWS_RID_EAX", "EAX")
            editor.putString("NWS_RID_EKA", "BHX")
            editor.putString("NWS_RID_EPZ", "EPZ")
            editor.putString("NWS_RID_EWX", "EWX")
            editor.putString("NWS_RID_FFC", "FFC")
            editor.putString("NWS_RID_FGF", "MVX")
            editor.putString("NWS_RID_FGZ", "FSX")
            editor.putString("NWS_RID_FSD", "FSD")
            editor.putString("NWS_RID_FWD", "FWS")
            editor.putString("NWS_RID_GGW", "GGW")
            editor.putString("NWS_RID_GID", "UEX")
            editor.putString("NWS_RID_GJT", "GJX")
            editor.putString("NWS_RID_GLD", "GLD")
            editor.putString("NWS_RID_GRB", "GRB")
            editor.putString("NWS_RID_GRR", "GRR")
            editor.putString("NWS_RID_GSP", "GSP")
            editor.putString("NWS_RID_GUM", "GUA")
            editor.putString("NWS_RID_GYX", "GYX")
            editor.putString("NWS_RID_HFO", "HMO")
            editor.putString("NWS_RID_HGX", "HGX")
            editor.putString("NWS_RID_HNX", "HNX")
            editor.putString("NWS_RID_HUN", "HTX")
            editor.putString("NWS_RID_ICT", "ICT")
            editor.putString("NWS_RID_ILM", "LTX")
            editor.putString("NWS_RID_ILN", "ILN")
            editor.putString("NWS_RID_ILX", "ILX")
            editor.putString("NWS_RID_IND", "IND")
            editor.putString("NWS_RID_IWX", "IWX")
            editor.putString("NWS_RID_JAN", "DGX")
            editor.putString("NWS_RID_JAX", "JAX")
            editor.putString("NWS_RID_JKL", "JKL")
            editor.putString("NWS_RID_KEY", "BYX")
            editor.putString("NWS_RID_LBF", "LNX")
            editor.putString("NWS_RID_LCH", "LCH")
            editor.putString("NWS_RID_LIX", "LIX")
            editor.putString("NWS_RID_LKN", "LRX")
            editor.putString("NWS_RID_LMK", "LVX")
            editor.putString("NWS_RID_LOT", "LOT")
            editor.putString("NWS_RID_LOX", "VTX")
            editor.putString("NWS_RID_LSX", "LSX")
            editor.putString("NWS_RID_LUB", "LBB")
            editor.putString("NWS_RID_LWX", "LWX")
            editor.putString("NWS_RID_LZK", "LZK")
            editor.putString("NWS_RID_MAF", "MAF")
            editor.putString("NWS_RID_MEG", "NQA")
            editor.putString("NWS_RID_MFL", "AMX")
            editor.putString("NWS_RID_MFR", "MAX")
            editor.putString("NWS_RID_MHX", "MHX")
            editor.putString("NWS_RID_MKX", "MKX")
            editor.putString("NWS_RID_MLB", "MLB")
            editor.putString("NWS_RID_MOB", "MOB")
            editor.putString("NWS_RID_MPX", "MPX")
            editor.putString("NWS_RID_MQT", "MQT")
            editor.putString("NWS_RID_MRX", "MRX")
            editor.putString("NWS_RID_MSO", "MSX")
            editor.putString("NWS_RID_MTR", "MUX")
            editor.putString("NWS_RID_OAX", "OAX")
            editor.putString("NWS_RID_OHX", "OHX")
            editor.putString("NWS_RID_OKX", "OKX")
            editor.putString("NWS_RID_OTX", "OTX")
            editor.putString("NWS_RID_OUN", "TLX")
            editor.putString("NWS_RID_PAH", "PAH")
            editor.putString("NWS_RID_PBZ", "PBZ")
            editor.putString("NWS_RID_PDT", "PDT")
            editor.putString("NWS_RID_PHI", "DIX")
            editor.putString("NWS_RID_PIH", "SFX")
            editor.putString("NWS_RID_PQR", "RTX")
            editor.putString("NWS_RID_PSR", "IWA")
            editor.putString("NWS_RID_PUB", "PUX")
            editor.putString("NWS_RID_RAH", "RAX")
            editor.putString("NWS_RID_REV", "RGX")
            editor.putString("NWS_RID_RIW", "RIW")
            editor.putString("NWS_RID_RLX", "RLX")
            editor.putString("NWS_RID_RNK", "FCX")
            editor.putString("NWS_RID_SEW", "ATX")
            editor.putString("NWS_RID_SGF", "SGF")
            editor.putString("NWS_RID_SGX", "NKX")
            editor.putString("NWS_RID_SHV", "SHV")
            editor.putString("NWS_RID_SJT", "SJT")
            editor.putString("NWS_RID_SJU", "JUA")
            editor.putString("NWS_RID_JSJ", "JUA")
            editor.putString("NWS_RID_SLC", "MTX")
            editor.putString("NWS_RID_STO", "DAX")
            editor.putString("NWS_RID_TAE", "TLH")
            editor.putString("NWS_RID_TBW", "TBW")
            editor.putString("NWS_RID_TFX", "TFX")
            editor.putString("NWS_RID_TOP", "TWX")
            editor.putString("NWS_RID_TSA", "INX")
            editor.putString("NWS_RID_TWC", "EMX")
            editor.putString("NWS_RID_UNR", "UDX")
            editor.putString("NWS_RID_VEF", "ESX")
            editor.putString("STATE_TW_ID_AL", "410946082747596800")
            editor.putString("STATE_TW_ID_AK", "410946674685509632")
            editor.putString("STATE_TW_ID_AZ", "410946812913008640")
            editor.putString("STATE_TW_ID_AR", "410946983583428608")
            editor.putString("STATE_TW_ID_CA", "410947133554966530")
            editor.putString("STATE_TW_ID_CO", "410947263117004802")
            editor.putString("STATE_TW_ID_CT", "410947401004773376")
            editor.putString("STATE_TW_ID_DE", "410947531611185153")
            editor.putString("STATE_TW_ID_FL", "410947683067498496")
            editor.putString("STATE_TW_ID_GA", "410947813162225664")
            editor.putString("STATE_TW_ID_HI", "410947943412137984")
            editor.putString("STATE_TW_ID_ID", "410948063646076928")
            editor.putString("STATE_TW_ID_IL", "410948185452838912")
            editor.putString("STATE_TW_ID_IN", "410948324535988224")
            editor.putString("STATE_TW_ID_IA", "410948449949847553")
            editor.putString("STATE_TW_ID_KS", "410948583387459584")
            editor.putString("STATE_TW_ID_KY", "410948713557663746")
            editor.putString("STATE_TW_ID_LA", "410948840821239810")
            editor.putString("STATE_TW_ID_ME", "410948966411300865")
            editor.putString("STATE_TW_ID_MD", "410949089140813824")
            editor.putString("STATE_TW_ID_MA", "410949206115762176")
            editor.putString("STATE_TW_ID_MI", "406095836829855744")
            editor.putString("STATE_TW_ID_MN", "410949323623395329")
            editor.putString("STATE_TW_ID_MS", "410949449737703424")
            editor.putString("STATE_TW_ID_MO", "410949571464806400")
            editor.putString("STATE_TW_ID_MT", "410949718403842048")
            editor.putString("STATE_TW_ID_NE", "410949838730035200")
            editor.putString("STATE_TW_ID_NV", "410949972331212800")
            editor.putString("STATE_TW_ID_NH", "410950086571474944")
            editor.putString("STATE_TW_ID_NJ", "410950242838646785")
            editor.putString("STATE_TW_ID_NM", "410950366134419457")
            editor.putString("STATE_TW_ID_NY", "410950487198793728")
            editor.putString("STATE_TW_ID_NC", "410950603993411584")
            editor.putString("STATE_TW_ID_ND", "410950714639138816")
            editor.putString("STATE_TW_ID_OH", "410950826153099264")
            editor.putString("STATE_TW_ID_OK", "410950956541415424")
            editor.putString("STATE_TW_ID_OR", "410951075554803712")
            editor.putString("STATE_TW_ID_PA", "410951192261316608")
            editor.putString("STATE_TW_ID_RI", "410951324608385026")
            editor.putString("STATE_TW_ID_SC", "410951462919745537")
            editor.putString("STATE_TW_ID_SD", "410951576107237376")
            editor.putString("STATE_TW_ID_TN", "410951698291507202")
            editor.putString("STATE_TW_ID_TX", "410951810052939777")
            editor.putString("STATE_TW_ID_UT", "410951924230279168")
            editor.putString("STATE_TW_ID_VT", "410952117885472768")
            editor.putString("STATE_TW_ID_VA", "410952264191205376")
            editor.putString("STATE_TW_ID_WA", "410952480776667136")
            editor.putString("STATE_TW_ID_WV", "410952602067550208")
            editor.putString("STATE_TW_ID_WI", "410952736549502977")
            editor.putString("STATE_TW_ID_WY", "410952874370162688")
            editor.apply()
        }
    }

    fun prefInitTwitterCA(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("STATE_TW_ID_bcstorm", null)
        if (value == null) {
            editor.putString("STATE_TW_ID_bcstorm", "489578049524879360")
            editor.putString("STATE_TW_ID_abstorm", "489578415377231872")
            editor.putString("STATE_TW_ID_skstorm", "489578619665014784")
            editor.putString("STATE_TW_ID_mbstorm", "489578784731848704")
            editor.putString("STATE_TW_ID_onstorm", "489710428696481795")
            editor.putString("STATE_TW_ID_nbstorm", "489711021922066432")
            editor.putString("STATE_TW_ID_pestorm", "489710770200932352")
            editor.putString("STATE_TW_ID_nsstorm", "489711312742522882")
            editor.putString("STATE_TW_ID_nlwx", "489711657912782848")
            editor.putString("STATE_TW_ID_ntstorm", "489754447413641217")
            editor.putString("STATE_TW_ID_meteoqc", "489754142907170816")
            editor.putString("STATE_TW_ID_st", "611565983380164608")
            editor.apply()
        }
    }

    fun prefInitRIDXY2(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("RID_hawaii_Y", null)
        if (value == null) {
            editor.putString("RID_latest_X", "36.105") // nws conus
            editor.putString("RID_latest_Y", "97.141")
            editor.putString("RID_centgrtlakes_X", "42.127")
            editor.putString("RID_centgrtlakes_Y", "84.544")
            editor.putString("RID_uppermissvly_X", "42.75")
            editor.putString("RID_uppermissvly_Y", "97.10")
            editor.putString("RID_northrockies_X", "42.75")
            editor.putString("RID_northrockies_Y", "108.60")
            editor.putString("RID_northeast_X", "42.425")
            editor.putString("RID_northeast_Y", "74.10")
            editor.putString("RID_pacnorthwest_X", "42.425")
            editor.putString("RID_pacnorthwest_Y", "120.10")
            editor.putString("RID_pacsouthwest_X", "35.15")
            editor.putString("RID_pacsouthwest_Y", "120.15")
            editor.putString("RID_southrockies_X", "32.5")
            editor.putString("RID_southrockies_Y", "110.50")
            editor.putString("RID_southplains_X", "31.6")
            editor.putString("RID_southplains_Y", "100.00")
            editor.putString("RID_southmissvly_X", "31.6")
            editor.putString("RID_southmissvly_Y", "90.00")
            editor.putString("RID_southeast_X", "29.86")
            editor.putString("RID_southeast_Y", "82.658")
            editor.putString("RID_hawaii_X", "19.91")
            editor.putString("RID_hawaii_Y", "157.55")
            editor.apply()
        }
    }
}



